version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${LOG_DIR}:/var/log/nginx/:rw
    restart: always
    networks:
      - default
  php72:
    build:
      "./"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${LOG_DIR}:/var/log/php:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default
  # socat:
  #   image: "alpine/socat"
  #   container_name: socat
  #   restart: "always"
  #   volumes:
  #   - "/var/run/docker.sock:/var/run/docker.sock"
  #   ports:
  #   - "2375:2375"
  #   command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"    
