version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - ${NGINX_HTTP_HOST_PORT}:80
      - ${NGINX_HTTPS_HOST_PORT}:443
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${LOG_DIR}:/var/log/nginx/:rw
    restart: always
    networks:
      - default
  php72:
    build:
      "./"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${LOG_DIR}:/var/log/php:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default
  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - ${REDIS_HOST_PORT}:6379
    volumes:
      - ${REDIS_CONF_FILE}:/usr/local/etc/redis.conf
      - ${REDIS_DATA_DIR}:/usr/local/redis/data
      - ${REDIS_LOG_DIR}:/usr/local/redis/redis.log
    restart: always
    networks:
      - default
  xunsearch:
    image: hightman/xunsearch:${XUNSEARCH_VERSION}
    ports:
      - ${XUNSEARCH_INDEX_PORT}:8383
      - ${XUNSEARCH_SEARCH_PORT}:8384
    volumes:
      - ${XUNSEARCH_DATA_DIR}:/usr/local/xunsearch/data
    restart: always
    networks:
      - default
  redisAdmin:
    image: erikdubbelboer/phpredisadmin:${REDISMYADMIN_VERSION}
    ports:
      - ${REDISMYADMIN_HOST_PORT}:80
    environment:
      - ADMIN_USER=${REDISMYADMIN_ADMIN_USER}
      - ADMIN_PASS=${REDISMYADMIN_ADMIN_PASS}
      - REDIS_1_HOST=${REDISMYADMIN_REDIS_1_HOST}
      - REDIS_1_PORT=${REDISMYADMIN_REDIS_1_PORT}
    links:
      - redis
    restart: always
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${REDISMYADMIN_VERSION}
    ports:
      - ${PHPMYADMIN_HOST_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${PHPMYADMIN_MYSQL_HOST}
      - PMA_PORT=${PHPMYADMIN_MYSQL_PORT}
      - PMA_USER=${PHPMYADMIN_MYSQL_USER}
      - PMA_PASSWORD=${PHPMYADMIN_MYSQL_PASSWORD}
    restart: always
    networks:
      - default


